src/Ben/DoctorsBundle/Entity/Person.php
<?php

namespace Ben\DoctorsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Person
 *
 * @ORM\Table(name="person")
 * @ORM\Entity(repositoryClass="Ben\DoctorsBundle\Entity\PersonRepository")
 */
class Person
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="cin", type="string", length=255)
     */
    private $cin;

    /**
     * @var string
     *
     * @ORM\Column(name="cne", type="string", length=255)
     */
    private $cne;

    /**
     * @var string
     *
     * @ORM\Column(name="firstname", type="string", length=255)
     */
    private $firstname;

    /**
     * @var string
     *
     * @ORM\Column(name="familyname", type="string", length=255)
     */
    private $familyname;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="birthday", type="date")
     */
    private $birthday;

    /**
     * @var string
     *
     * @ORM\Column(name="birthcity", type="string", length=255, nullable=true)
     */
    private $birthcity;

    /**
     * @var string
     *
     * @ORM\Column(name="gender", type="string", length=255)
     */
    private $gender;

    /**
     * @var string
     *
     * @ORM\Column(name="contry", type="string", length=255, nullable=true)
     */
    private $contry;

    /**
     * @var string
     *
     * @ORM\Column(name="city", type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @var string
     *
     * @ORM\Column(name="address", type="string", length=255, nullable=true)
     */
    private $address;

    /**
     * @var string
     *
     * @ORM\Column(name="etablissement", type="string", length=255, nullable=true)
     */
    private $etablissement;

    /**
     * @var string
     *
     * @ORM\Column(name="university", type="string", length=255, nullable=true)
     */
    private $university;

    /**
     * @var string
     *
     * @ORM\Column(name="gsm", type="string", length=255, nullable=true)
     */
    private $gsm;

    /**
     * @var string
     *
     * @ORM\Column(name="cnss", type="string", length=255)
     */
    private $cnss;

    /**
     * @var string
     *
     * @ORM\Column(name="cnsstype", type="string", length=255)
     */
    private $cnsstype;

    /**
     * @var string
     *
     * @ORM\Column(name="parent_name", type="string", length=255, nullable=true)
     */
    private $parentName;

    /**
     * @var string
     *
     * @ORM\Column(name="parent_address", type="string", length=255, nullable=true)
     */
    private $parentAddress;

    /**
     * @var string
     *
     * @ORM\Column(name="parent_gsm", type="string", length=255, nullable=true)
     */
    private $parentGsm;

    /**
     * @var string
     *
     * @ORM\Column(name="parent_fixe", type="string", length=255, nullable=true)
     */
    private $parentFixe;

    /**
     * @var boolean
     * @ORM\Column(name="ishandicap", type="boolean", nullable=true)
     * 
     */
    private $ishandicap;

    /**
     * @var string
     *
     * @ORM\Column(name="handicap", type="string", length=255, nullable=true)
     */
    private $handicap;

    /**
     * @var string
     *
     * @ORM\Column(name="needs", type="text", nullable=true)
     */
    private $needs;

    /**
     * @var boolean
     *
     * @ORM\Column(name="resident", type="boolean")
     */
    private $resident;

    /**
     * @var \DateTime $created
     *
     * @ORM\Column(name="created", type="datetime")
     */
    protected $created;

    /**
    * @ORM\OneToMany(targetEntity="Ben\DoctorsBundle\Entity\Antecedent", mappedBy="person", cascade={"remove", "persist"})
    */
    protected $antecedents;

    /**
    * @ORM\OneToMany(targetEntity="Ben\DoctorsBundle\Entity\Consultation", mappedBy="person", cascade={"remove", "persist"})
    */
    protected $consultations;
    
    /************ constructeur ************/
    
    public function __construct()
    {
        $this->birthday =  new \DateTime;
        $this->created = new \DateTime;
        $this->antecedents = new \Doctrine\Common\Collections\ArrayCollection();
        $this->consultations = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    /************ getters & setters  ************/

   /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get FullName
     *
     * @return string 
     */
    public function __toString()
    {
        return $this->getFullName();
    }

    /**
     * Set cin
     *
     * @param string $cin
     * @return Person
     */
    public function setCin($cin)
    {
        $this->cin = $cin;

        return $this;
    }

    /**
     * Get cin
     *
     * @return string 
     */
    public function getCin()
    {
        return $this->cin;
    }

    /**
     * Set cne
     *
     * @param string $cne
     * @return Person
     */
    public function setCne($cne)
    {
        $this->cne = $cne;

        return $this;
    }

    /**
     * Get cne
     *
     * @return string 
     */
    public function getCne()
    {
        return $this->cne;
    }

    /**
     * Set firstname
     *
     * @param string $firstname
     * @return Person
     */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Get firstname
     *
     * @return string 
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Set familyname
     *
     * @param string $familyname
     * @return Person
     */
    public function setFamilyname($familyname)
    {
        $this->familyname = $familyname;

        return $this;
    }

    /**
     * Get familyname
     *
     * @return string 
     */
    public function getFamilyname()
    {
        return $this->familyname;
    }

    /**
     * Get FullName
     *
     * @return string 
     */
    public function getFullName()
    {
        return $this->familyname.' '.$this->firstname;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Person
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set birthday
     *
     * @param \DateTime $birthday
     * @return Person
     */
    public function setBirthday($birthday)
    {
        $this->birthday = $birthday;

        return $this;
    }

    /**
     * Get birthday
     *
     * @return \DateTime 
     */
    public function getBirthday()
    {
        return $this->birthday;
    }

    /**
     * Set birthcity
     *
     * @param string $birthcity
     * @return Person
     */
    public function setBirthcity($birthcity)
    {
        $this->birthcity = $birthcity;

        return $this;
    }

    /**
     * Get birthcity
     *
     * @return string 
     */
    public function getBirthcity()
    {
        return $this->birthcity;
    }

    /**
     * Set gender
     *
     * @param string $gender
     * @return Person
     */
    public function setGender($gender)
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * Get gender
     *
     * @return string 
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * Set contry
     *
     * @param string $contry
     * @return Person
     */
    public function setContry($contry)
    {
        $this->contry = $contry;

        return $this;
    }

    /**
     * Get contry
     *
     * @return string 
     */
    public function getContry()
    {
        return $this->contry;
    }

    /**
     * Set city
     *
     * @param string $city
     * @return Person
     */
    public function setCity($city)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Get city
     *
     * @return string 
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Set address
     *
     * @param string $address
     * @return Person
     */
    public function setAddress($address)
    {
        $this->address = $address;

        return $this;
    }

    /**
     * Get address
     *
     * @return string 
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Set etablissement
     *
     * @param string $etablissement
     * @return Person
     */
    public function setEtablissement($etablissement)
    {
        $this->etablissement = $etablissement;

        return $this;
    }

    /**
     * Get etablissement
     *
     * @return string 
     */
    public function getEtablissement()
    {
        return $this->etablissement;
    }

    /**
     * Set university
     *
     * @param string $university
     * @return Person
     */
    public function setUniversity($university)
    {
        $this->university = $university;

        return $this;
    }

    /**
     * Get university
     *
     * @return string 
     */
    public function getUniversity()
    {
        return $this->university;
    }

    /**
     * Set gsm
     *
     * @param string $gsm
     * @return Person
     */
    public function setGsm($gsm)
    {
        $this->gsm = $gsm;

        return $this;
    }

    /**
     * Get gsm
     *
     * @return string 
     */
    public function getGsm()
    {
        return $this->gsm;
    }

    /**
     * Set cnss
     *
     * @param string $cnss
     * @return Person
     */
    public function setCnss($cnss)
    {
        $this->cnss = $cnss;

src/Ben/DoctorsBundle/Form/AntecedentType.php
<?php

namespace Ben\DoctorsBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class AntecedentType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('allergies')
            ->add('autres')
            ->add('traitement')
            ->add('chirurgicaux')
            ->add('type', 'choice', array('choices' => array('Antecedents personnels' => 'Antecedents personnels','Antecedents familiaux' => 'Antecedents familiaux')))
            ->add('person')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Ben\DoctorsBundle\Entity\Antecedent'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'ben_antecedent';
    }
}

src/Ben/DoctorsBundle/Controller/AntecedentController.php
<?php

namespace Ben\DoctorsBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use JMS\SecurityExtraBundle\Annotation\Secure;

use Ben\DoctorsBundle\Entity\Antecedent;
use Ben\DoctorsBundle\Form\AntecedentType;
use Ben\DoctorsBundle\Entity\Person;

/**
 * Antecedent controller.
 *
 */
class AntecedentController extends Controller
{

    /**
     * Lists all Antecedent entities.
     * @Secure(roles="ROLE_USER")
     *
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('BenDoctorsBundle:Antecedent')->findAll();

        return $this->render('BenDoctorsBundle:Antecedent:index.html.twig', array(
            'entities' => $entities,
        ));
    }
    /**
     * Creates a new Antecedent entity.
     * @Secure(roles="ROLE_USER")
     *
     */
    public function createAction(Request $request)
    {
        $entity = new Antecedent();
        $form = $this->createForm(new AntecedentType(), $entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('person_show', array('id' => $entity->getPerson()->getId())));
        }

        return $this->render('BenDoctorsBundle:Antecedent:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView(),
        ));
    }

    /**
     * Displays a form to create a new Antecedent entity.
     * @Secure(roles="ROLE_USER")
     *
     */
    public function newAction(Person $person)
    {
        $entity = new Antecedent();
        $entity->setPerson($person);
        $form = $this->createForm(new AntecedentType(), $entity);

        return $this->render('BenDoctorsBundle:Antecedent:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView(),
        ));
    }

    /**
     * Finds and displays a Antecedent entity.
     * @Secure(roles="ROLE_USER")
     *
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('BenDoctorsBundle:Antecedent')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Antecedent entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return $this->render('BenDoctorsBundle:Antecedent:show.html.twig', array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing Antecedent entity.
     * @Secure(roles="ROLE_USER")
     *
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('BenDoctorsBundle:Antecedent')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Antecedent entity.');
        }

        $editForm = $this->createForm(new AntecedentType(), $entity);
        $deleteForm = $this->createDeleteForm($id);

        return $this->render('BenDoctorsBundle:Antecedent:edit.html.twig', array(
            'entity'      => $entity,
            'form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }
    /**
     * Edits an existing Antecedent entity.
     * @Secure(roles="ROLE_USER")
     *
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('BenDoctorsBundle:Antecedent')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Antecedent entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createForm(new AntecedentType(), $entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $em->flush();

            return $this->redirect($this->generateUrl('antecedent_edit', array('id' => $id)));
        }

        return $this->render('BenDoctorsBundle:Antecedent:edit.html.twig', array(
            'entity'      => $entity,
            'form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }
    /**
     * Deletes a Antecedent entity.
     * @Secure(roles="ROLE_ADMIN")
     *
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('BenDoctorsBundle:Antecedent')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Antecedent entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('antecedent'));
    }

    /**
     * Creates a form to delete a Antecedent entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder(array('id' => $id))
            ->add('id', 'hidden')
            ->getForm()
        ;
    }
}

src/Ben/DoctorsBundle/Resources/views/Antecedent/edit.html.twig
{% extends "BenDoctorsBundle::layout.html.twig" %}
{% block title %}
Tableau de bord | {{ parent() }}
{% endblock %}
{% block body %}
<h3><span class="glyphicon glyphicon-user"></span> Mise à jour d'un Antecedent medicale</h3>

<form action="{{ path('antecedent_update', { 'id': entity.id }) }}"  class="form-horizontal col-md-8" method="post">
    <div class="form-group ">
        <label class="col-md-6 control-label" for="user">Etudiant</label>
        <div class="col-md-6">
            <input id="user" class="form-control disabled" disabled="disabled" type="text" name="unused" value="{{ entity.person.fullName }}">
        </div>
    </div>
    {% include "BenDoctorsBundle:Antecedent:form.html.twig" %}

    <div class="form-group">
      <div class="col-sm-offset-6 col-sm-6">
        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span> Mettre à jour</button>
        <a href="#" id="js-delete" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span> Supprimer</a>
      </div>
    </div>
</form>
<form id="deleteForm" action="{{ path('antecedent_delete', { 'id': entity.id }) }}" method="DELETE" class="">
    {{ form_widget(delete_form) }}
</form>

{% endblock %}
{% block javascripts %}
{{ parent() }}
<script> 
    (function($) {
    	$('#ben_antecedent_person').closest('.form-group').hide();
        $('#js-delete').on('click', function(){
            $('#deleteForm').submit();
            return false;
        });
        $('select').removeClass('form-control').select2({minimumResultsForSearch: -1});
    })(jQuery);
</script>
{% endblock %}

src/Ben/DoctorsBundle/Resources/views/Antecedent/form.html.twig
  {{ form_row(form.type, { 'label': 'type'}) }}
  {{ form_row(form.allergies, { 'label': 'allergies'}) }}
  {{ form_row(form.autres, { 'label': 'autres'}) }}
  {{ form_row(form.traitement, { 'label': 'Traitement en cours'}) }}
  {{ form_row(form.chirurgicaux, { 'label': 'Antecédents chirurgicaux'}) }}
  {{ form_row(form.person) }}
  {{ form_rest(form) }} 
      

src/Ben/DoctorsBundle/Resources/views/Antecedent/index.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Antecedent list</h1>

    <table class="records_list">
        <thead>
            <tr>
                <th>Id</th>
                <th>Allergies</th>
                <th>Autres</th>
                <th>Traitement</th>
                <th>Chirurgicaux</th>
                <th>Type</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for entity in entities %}
            <tr>
                <td><a href="{{ path('antecedent_show', { 'id': entity.id }) }}">{{ entity.id }}</a></td>
                <td>{{ entity.allergies }}</td>
                <td>{{ entity.autres }}</td>
                <td>{{ entity.traitement }}</td>
                <td>{{ entity.chirurgicaux }}</td>
                <td>{{ entity.type }}</td>
                <td>
                <ul>
                    <li>
                        <a href="{{ path('antecedent_show', { 'id': entity.id }) }}">show</a>
                    </li>
                    <li>
                        <a href="{{ path('antecedent_edit', { 'id': entity.id }) }}">edit</a>
                    </li>
                </ul>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

        <ul>
        <li>
            <a href="{{ path('antecedent_new') }}">
                Create a new entry
            </a>
        </li>
    </ul>
    {% endblock %}

src/Ben/DoctorsBundle/Resources/views/Antecedent/new.html.twig
{% extends "BenDoctorsBundle::layout.html.twig" %}
{% block title %}
Tableau de bord | {{ parent() }}
{% endblock %}
{% block body %}
<h3><span class="glyphicon glyphicon-tag"></span> Ajout d'un Antecedent</h3>
<form action="{{ path('antecedent_create') }}" class="form-horizontal col-md-8" method="post" {{ form_enctype(form) }}>
    <div class="form-group ">
		<label class="col-md-6 control-label" for="user">Etudiant</label>
		<div class="col-md-6">
			<input id="user" class="form-control disabled" disabled="disabled" type="text" name="unused" value="{{ entity.person.fullName }}">
		</div>
	</div>

    {% include "BenDoctorsBundle:antecedent:form.html.twig" %}

    <div class="form-group">
      <div class="col-md-offset-6 col-md-6">
        <button type="submit" name="subvalider" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span> Ajouter</button>
      </div>
    </div>
</form>

{% endblock body %}
{% block javascripts %}
{{ parent() }}
<script> 
    (function($) {
        $('#ben_antecedent_person').closest('.form-group').hide();
        $('select').removeClass('form-control').select2({minimumResultsForSearch: -1});
    })(jQuery);
</script>
{% endblock %}

src/Ben/DoctorsBundle/Resources/views/Antecedent/show.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Antecedent</h1>

    <table class="record_properties">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ entity.id }}</td>
            </tr>
            <tr>
                <th>Allergies</th>
                <td>{{ entity.allergies }}</td>
            </tr>
            <tr>
                <th>Autres</th>
                <td>{{ entity.autres }}</td>
            </tr>
            <tr>
                <th>Traitement</th>
                <td>{{ entity.traitement }}</td>
            </tr>
            <tr>
                <th>Chirurgicaux</th>
                <td>{{ entity.chirurgicaux }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ entity.type }}</td>
            </tr>
        </tbody>
    </table>

        <ul class="record_actions">
    <li>
        <a href="{{ path('antecedent') }}">
            Back to the list
        </a>
    </li>
    <li>
        <a href="{{ path('antecedent_edit', { 'id': entity.id }) }}">
            Edit
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}